#!/bin/sh
#
# Copyright 2009 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This is a control script for sitemapservice binary.
# Currently, it is very straight forward, as this script only add the
# httpd configuration file arg to sitemapservice's command line.

# ensure user is root
if [ $(id -u) != 0 ]; then
  echo "Permission denied: require superuser"
  exit 1
fi

# path to binary sitemapservice
SERVICE="/usr/share/google-sitemap-generator/sitemap-daemon"

if test -f $SERVICE; then :; else
  echo "Binary file can't be found."
  exit 1
fi

# invoke the binary
# $SERVICE $@ "httpdconf=$APACHECONF"
$SERVICE $@

exit $?
